/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.lmts;

import com.lmts.Dao.UserDao;
import com.lmts.helpers.DBUtils;
import com.lmts.model.User;
import com.lmts.service.UserService;
import java.awt.Image;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author sudip
 */
public class HomeJPanelHomePanel extends javax.swing.JPanel {
    private UserService userService;
    /**
     * Creates new form HomeJPanelHomePanel
     */
    public HomeJPanelHomePanel() {
        initComponents();
        this.userService = new UserService();
       
    }
    
    private  void getUserList(){
        List<User> userList = this.userService.getAllUsers();
        for(User user : userList){
            System.out.println("User ID: " + user.getId());
            System.out.println("User Name: " + user.getUserName());
            System.out.println("Password : " + user.getPassword());
            System.out.println("Email: " + user.getEmail());
            System.out.println("-------------");
        }
    }
    
    private void scaleCoverImage(){
        ImageIcon icon = new ImageIcon("/com/lmts/assets/images/cover-image.jpg");
        
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        jLabel1.setIcon(scaledIcon);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
