
package com.lmts;

import com.lmts.model.MusicModel;
import com.lmts.service.MusicService;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;


public class HomeJPanelMusicListPanel extends javax.swing.JPanel {

    /**
     * Creates new form HomeJPanelMusicListPanel
     */
    private JPanel cardsPanel;
    private static MusicService musicService;
    
    public HomeJPanelMusicListPanel() {
          initComponents();
            HomeJPanelMusicListPanel.musicService = new MusicService();
            setLayout(new BorderLayout());

            // Create a panel to hold the cards
            cardsPanel = new JPanel();
            cardsPanel.setLayout(new BoxLayout(cardsPanel, BoxLayout.Y_AXIS));

            // Add a JScrollPane to the cardsPanel
            JScrollPane scrollPane = new JScrollPane(cardsPanel);
            scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);

            // Add the scroll pane to the layout
            add(scrollPane, BorderLayout.CENTER);
//            this.customInitComponents();
            this.addMusciCardList();
            
    }
    
    public void updateMusicList() {
        cardsPanel.removeAll(); // Clear existing cards
        List<MusicListCardJPanel> musicCards = createMusicCards(); // Re-create music cards
        for (MusicListCardJPanel musicCard : musicCards) {
            cardsPanel.add(musicCard);
            revalidate(); // Refresh the layout
            repaint(); // Repaint the container
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    
//    public void customInitComponents(){
//       setLayout(new java.awt.GridLayout(2, 2));
//    }
    
    private  void addMusciCardList(){
        List<MusicListCardJPanel> musicCards = createMusicCards(); // Create a list of music cards

            for (MusicListCardJPanel musicCard : musicCards) {
                
                this.cardsPanel.add(musicCard);
                revalidate(); // Refresh the layout
                repaint(); // Repaint the container
            }
    }
    
    private static List<MusicListCardJPanel> createMusicCards() {
        List<MusicListCardJPanel> musicCards = new ArrayList<>();
        
        List<MusicModel> musicList = HomeJPanelMusicListPanel.musicService.getALlMusicList();
        
        for(MusicModel music:musicList){
            MusicListCardJPanel musicCard = new MusicListCardJPanel(music.getMusicName(), music.getTime(), music.getDate(),music.getAvailableSeat(),music.getMusicDescription());
            musicCards.add(musicCard);
        }

        return musicCards;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
